# Generated by Django 4.1.3 on 2022-11-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='date',
            field=models.DateField(auto_now_add=True, default='2022-11-10'),
            preserve_default=False,
        ),
    ]
