# Generated by Django 4.1.3 on 2022-11-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0002_dailydata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='total_calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
