# Generated by Django 4.1.3 on 2022-11-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0003_dailydata_total_calories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailydata',
            options={'verbose_name_plural': 'Daily Data'},
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='date',
            field=models.DateField(),
        ),
    ]
