# Generated by Django 4.1.3 on 2022-11-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0004_alter_dailydata_options_alter_dailydata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
