# Generated by Django 4.1.3 on 2022-11-08 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('burnt_calories_per_min', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories_per_100g', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fats_per_100g', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_per_100g', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs_per_100g', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('grams', models.PositiveIntegerField()),
                ('fats_grams', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('protein_grams', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('carbs_grams', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
