# Generated by Django 4.1.3 on 2022-11-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('details', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('meals', models.ManyToManyField(to='core.meal')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
