# Generated by Django 4.1.3 on 2022-11-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_foodplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplan',
            name='foods',
            field=models.ManyToManyField(blank=True, to='core.food'),
        ),
    ]
