# Generated by Django 4.1.3 on 2022-11-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0003_dailydata_total_calories'),
        ('core', '0008_rename_burnt_calories_per_min_exercise_metabolic_equivalent'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='daily_data_pk',
            field=models.ManyToManyField(blank=True, null=True, to='calorie_counter.dailydata'),
        ),
    ]
