# Generated by Django 4.1.3 on 2022-11-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0003_dailydata_total_calories'),
        ('core', '0009_exercise_daily_data_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='daily_data_pk',
            field=models.ManyToManyField(blank=True, to='calorie_counter.dailydata'),
        ),
    ]
