# Generated by Django 4.1.3 on 2022-11-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0003_dailydata_total_calories'),
        ('core', '0010_alter_exercise_daily_data_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='daily_data_pk',
            field=models.ManyToManyField(blank=True, to='calorie_counter.dailydata'),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='daily_data_pk',
            field=models.ManyToManyField(blank=True, to='calorie_counter.dailydata'),
        ),
        migrations.AddField(
            model_name='meal',
            name='daily_data_pk',
            field=models.ManyToManyField(blank=True, to='calorie_counter.dailydata'),
        ),
    ]
