# Generated by Django 4.1.3 on 2022-11-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_add_motivations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='add_motivations',
            new_name='motivations_group',
        ),
    ]
